/**
 * OrderManagement.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Contact { 
    readonly id?: string;
    readonly dateCreated?: string;
    readonly dateModified?: string;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    street?: string | null;
    city?: string | null;
    postalCode?: string | null;
    country?: string | null;
    state?: string | null;
    email?: string | null;
    phone?: string | null;
}

